# Generated by Django 3.2.10 on 2022-04-07 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_reachouts'),
    ]

    operations = [
        migrations.AddField(
            model_name='reachouts',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
